# Generated by Django 5.1.3 on 2024-11-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username_onetimepasscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepasscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onetimepasscode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
