# Generated by Django 5.1.3 on 2024-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("Nom de l'ecole", models.CharField(max_length=100)),
                ('Code du pays', models.CharField(max_length=3)),
                ('Pays', models.CharField(blank=True, max_length=120, null=True)),
                ('Ville', models.CharField(blank=True, max_length=120, null=True)),
                ("Domaine d'etude", models.CharField(blank=True, max_length=120, null=True)),
                ('Score requis', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('Frais de dossier', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
            },
        ),
    ]
