# Generated by Django 5.1.3 on 2024-11-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'ecole")),
                ('country_code', models.CharField(max_length=3, verbose_name='Code du pays')),
                ('country_name', models.CharField(max_length=120, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ville')),
                ('website', models.URLField(max_length=100, verbose_name='Site Web')),
                ('domain', models.CharField(blank=True, max_length=120, null=True, verbose_name="Domaine d'etude")),
                ('require_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Score requis')),
                ('documents_fees', models.CharField(blank=True, max_length=60, null=True, verbose_name='Frais de dossier')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('degree', models.CharField(max_length=120, verbose_name='Niveau')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='school.university', verbose_name='Université')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
    ]
