# Generated by Django 5.1.3 on 2024-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Code du pays',
        ),
        migrations.RemoveField(
            model_name='university',
            name="Domaine d'etude",
        ),
        migrations.RemoveField(
            model_name='university',
            name='Frais de dossier',
        ),
        migrations.RemoveField(
            model_name='university',
            name="Nom de l'ecole",
        ),
        migrations.RemoveField(
            model_name='university',
            name='Pays',
        ),
        migrations.RemoveField(
            model_name='university',
            name='Score requis',
        ),
        migrations.RemoveField(
            model_name='university',
            name='Ville',
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='university',
            name='country_code',
            field=models.CharField(default=1, max_length=3, verbose_name='Code du pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='country_name',
            field=models.CharField(default=1, max_length=120, verbose_name='Pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='documents_fees',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Frais de dossier'),
        ),
        migrations.AddField(
            model_name='university',
            name='domain',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Domaine d'etude"),
        ),
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name="Nom de l'ecole"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='require_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, verbose_name='Score requis'),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(default=1, max_length=100, verbose_name='Site Web'),
            preserve_default=False,
        ),
    ]
