# Generated by Django 5.1.3 on 2024-11-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date de naissance', models.DateField(blank=True, null=True)),
                ("Pays d'origine", models.CharField(blank=True, max_length=100, null=True)),
                ("Niveau d'etude", models.CharField(blank=True, max_length=100, null=True)),
                ('Serie BAC', models.CharField(blank=True, max_length=100, null=True)),
                ('Score moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
    ]
