# Generated by Django 5.1.3 on 2024-11-23 09:31

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image de profil')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('country_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name="Pays d'origine")),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('education_level', models.CharField(blank=True, choices=[('bac', 'BAC'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('cap', 'CAP')], max_length=100, null=True, verbose_name="Niveau d'étude")),
                ('bac_serie', models.CharField(blank=True, choices=[('tll', 'Terminale Lettre et Littérature (TLL)'), ('tseco', 'Terminale Science Économique (TSECO)'), ('tss', 'Terminale Science Exacte (TSS)')], max_length=5, null=True, verbose_name='Série BAC')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Score moyen')),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
    ]
