# Generated by Django 5.1.3 on 2024-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de telephone'),
        ),
    ]
